### ISSUE TITLE
Is android 13 supported? 

### ISSUE THREAD

**Issue by Loukious** [xiaowine/Lyrics-Getter#62]
**Describe the bug**
Everything is enabled correctly on lsposed but the module can't seem to work at all. I'm testing it using a supported version of APlayer 

**Smartphone (please complete the following information):**
 - Device: Poco x3 Pro 
 - OS: Android 13 Q3 on crDroid 

**Additional context**
The module is not picking up anything whatsoever which makes me think it's not correctly listening to the media events (maybe because of my android version?).

**Comment by xiaowine** [comment]
Android 13 is supported, and my device is.

**Comment by Loukious** [comment]
> Android 13 is supported, and my device is.

Any clue how can I get some logs or try to debug this?

**Comment by Loukious** [comment]
> Android 13 is supported, and my device is.

![Screenshot_20231021-030657_Logcat Extreme](https://github.com/xiaowine/Lyric-Getter/assets/24696530/bf18738d-1ffd-4c81-a113-9f17f8f10024)
Maybe these logs will help identify the issue?

**Comment by YouCanAi** [comment]
The log you gave shows that statusbar.finder is working properly and pushing the lyrics to Lyrics Getter, but the problem is that it is not displaying the lyrics in the statusbar.

My suggestion for this issue is to check if [StatusBarLyrics](https://github.com/Block-Network/StatusBarLyric) is installed on your device and configured correctly.

Note that Lyrics Getter is just a lyrics extractor and does not include the status bar lyrics feature. The lyrics displayed by [StatusBarLyrics](https://github.com/Block-Network/StatusBarLyric) need to be provided by Lyrics Getter, and the two complement each other.
